#!/usr/bin/env python3
"""
Interactive setup wizard for Hermes Avatar (Rail).

Guides users through configuration without hardcoding sensitive data in the repo.
Creates:
  - .env (Discord bot token, API keys - gitignored)
  - config.local.yaml (channel IDs, custom settings - gitignored)

Run this ONCE before using the application:
  python setup.py
"""

import os
import sys
import yaml
from pathlib import Path
from getpass import getpass

# Colors for terminal output
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
RESET = "\033[0m"

def print_header(text: str):
    print(f"\n{BLUE}{'='*60}{RESET}")
    print(f"{BLUE}{text}{RESET}")
    print(f"{BLUE}{'='*60}{RESET}\n")

def print_success(text: str):
    print(f"{GREEN}✓ {text}{RESET}")

def print_warning(text: str):
    print(f"{YELLOW}⚠ {text}{RESET}")

def print_error(text: str):
    print(f"{RED}✗ {text}{RESET}")

def print_info(text: str):
    print(f"  {text}")

def ask_yes_no(question: str, default: bool = True) -> bool:
    """Ask a yes/no question with default."""
    prefix = "Y/n" if default else "y/N"
    while True:
        answer = input(f"{question} [{prefix}]: ").strip().lower()
        if answer in ['', 'y', 'yes']:
            return True
        elif answer in ['n', 'no']:
            return False
        print_warning("Please answer 'yes' or 'no'")

def ask_input(question: str, default: str = None, required: bool = False) -> str:
    """Ask for input with optional default."""
    suffix = f" (default: {default})" if default else ""
    while True:
        answer = input(f"{question}{suffix}: ").strip()
        if answer:
            return answer
        elif default:
            return default
        elif not required:
            return ""
        else:
            print_warning("This field is required")

def setup_discord():
    """Configure Discord integration."""
    print_header("🤖 Discord Configuration")
    
    print_info("Rail needs to connect to Discord to communicate with Hermes.")
    print_info("You need a Discord bot with access to the channel.")
    print()
    
    # Create .env file
    env_path = Path(".env")
    
    # Discord bot token
    print_info("To get a Discord bot token:")
    print_info("  1. Go to https://discord.com/developers/applications")
    print_info("  2. Create a new application")
    print_info("  3. Go to 'Bot' section and create a bot")
    print_info("  4. Copy the token and paste it below")
    print_info("  5. Invite the bot to your server with these scopes:")
    print_info("     - bot")
    print_info("     - messages.read")
    print_info("     - messages.send")
    print_info("     - message_content intent (enabled in bot settings)")
    print()
    
    bot_token = getpass("Discord Bot Token: ").strip()
    
    if not bot_token:
        print_error("Bot token is required!")
        return False
    
    # Channel ID
    channel_id = ask_input(
        "Discord Channel ID (where Rail will communicate)",
        default="1552636595532865587"
    )
    
    # Hermes user ID
    hermes_user_id = ask_input(
        "Hermes User ID (the bot/user that responds)",
        default="371369636924751873"
    )
    
    # Write .env file
    env_content = f"""# Discord Configuration (generated by setup.py)
# DO NOT commit this file to git!

# Discord bot token for Rail to communicate with Hermes
DISCORD_BOT_TOKEN={bot_token}

# Optional: Other API keys (add as needed)
# HERMES_API_KEY=
# LLM_API_KEY=
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print_success(f"Created {env_path}")
    
    # Write config.local.yaml
    config_local_path = Path("config.local.yaml")
    config_local = {
        "discord": {
            "channel_id": channel_id,
            "hermes_user_id": hermes_user_id
        }
    }
    
    with open(config_local_path, 'w') as f:
        yaml.dump(config_local, f, default_flow_style=False)
    
    print_success(f"Created {config_local_path}")
    
    return True

def setup_screen_capture():
    """Configure screen capture settings."""
    print_header("📸 Screen Capture Configuration")
    
    print_info("Rail can capture your screen periodically and send to Hermes for analysis.")
    print()
    
    interval = ask_input(
        "Capture interval in seconds (5-60)",
        default="30"
    )
    
    try:
        interval = int(interval)
        if interval < 5 or interval > 60:
            print_warning("Interval should be between 5 and 60 seconds. Using default: 30")
            interval = 30
    except ValueError:
        print_warning("Invalid interval. Using default: 30")
        interval = 30
    
    # Update config.yaml (keep as template, user can override in config.local.yaml)
    config_path = Path("config.yaml")
    if config_path.exists():
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        
        if 'screen_capture' not in config:
            config['screen_capture'] = {}
        config['screen_capture']['interval_seconds'] = interval
        config['screen_capture']['enabled'] = True
        
        with open(config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False)
        
        print_success(f"Updated screen capture interval in {config_path}")
    
    return True

def setup_avatars():
    """Configure avatar settings."""
    print_header("👾 Avatar Configuration")
    
    print_info("Configure the appearance and behavior of the Hermes Girl avatar.")
    print()
    
    width = ask_input("Avatar width (pixels)", default="200")
    height = ask_input("Avatar height (pixels)", default="200")
    position = ask_input(
        "Avatar position on screen",
        default="top-right",
        required=False
    )
    
    # Valid positions
    valid_positions = ["top-left", "top-right", "bottom-left", "bottom-right"]
    if position not in valid_positions:
        print_warning(f"Invalid position. Using default: top-right")
        position = "top-right"
    
    # Update config.yaml
    config_path = Path("config.yaml")
    if config_path.exists():
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        
        if 'avatar' not in config:
            config['avatar'] = {}
        config['avatar']['width'] = int(width)
        config['avatar']['height'] = int(height)
        config['avatar']['position'] = position
        
        with open(config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False)
        
        print_success(f"Updated avatar settings in {config_path}")
    
    return True

def verify_setup():
    """Verify the setup is complete."""
    print_header("✅ Verification")
    
    checks = [
        (".env", "Discord credentials file"),
        ("config.local.yaml", "Local configuration file"),
        ("requirements.txt", "Dependencies file"),
    ]
    
    all_ok = True
    for path, description in checks:
        if Path(path).exists():
            print_success(f"{description} ({path})")
        else:
            print_error(f"{description} ({path}) - MISSING")
            all_ok = False
    
    # Check discord.py installation
    try:
        import discord
        print_success("discord.py installed")
    except ImportError:
        print_error("discord.py not installed")
        print_info("Run: pip install discord.py")
        all_ok = False
    
    return all_ok

def main():
    """Main setup wizard."""
    print_header("🚀 Hermes Avatar (Rail) Setup Wizard")
    
    print_info("This wizard will guide you through configuring Rail.")
    print_info("All sensitive data will be stored in git-ignored files.")
    print()
    
    # Check if already configured
    env_exists = Path(".env").exists()
    config_local_exists = Path("config.local.yaml").exists()
    
    if env_exists or config_local_exists:
        print_warning("Rail appears to be already configured!")
        if not ask_yes_no("Do you want to reconfigure?", default=False):
            print_info("Setup cancelled.")
            return
    
    # Run setup steps
    steps = [
        ("Discord Configuration", setup_discord),
        ("Screen Capture Configuration", setup_screen_capture),
        ("Avatar Configuration", setup_avatars),
    ]
    
    for name, step_func in steps:
        if not step_func():
            print_error(f"Setup failed at {name}")
            return
    
    # Verify setup
    if verify_setup():
        print_header("🎉 Setup Complete!")
        print()
        print_info("Next steps:")
        print_info("  1. Install dependencies: pip install -r requirements.txt")
        print_info("  2. Test the application: python -m hermes_avatar.main")
        print_info("  3. Make sure the Discord bot is invited to your server!")
        print()
        print_info("Files created:")
        print_info("  - .env (Discord token and API keys - DO NOT COMMIT)")
        print_info("  - config.local.yaml (local settings - DO NOT COMMIT)")
        print()
        print_info("Remember to:")
        print_info("  - Enable 'message_content' intent for your bot in Discord Developer Portal")
        print_info("  - Invite the bot with scopes: bot, messages.read, messages.send")
        print()
    else:
        print_error("Setup completed with errors. Please fix the issues above.")

if __name__ == "__main__":
    main()
