#!/usr/bin/env python3
"""
Interactive setup wizard for Hermes Avatar (Rail).

Two communication channels, independently selectable:

  [A] Hermes API (recommended, default ON): direct HTTP connection to the
      Hermes Agent gateway "api_server" platform (OpenAI-compatible).
      Works on localhost (no TLS) or remote (https:// or VPN tunnel).
  [B] Discord (optional, default OFF): chat via a Discord bot, as fallback.

All settings live in .env (gitignored). Nothing else to configure by hand.

Usage:
  python setup.py            interactive wizard
  python setup.py --check    verify current .env and test connectivity
"""

import os
import re
import sys
from pathlib import Path
from getpass import getpass

try:
    import yaml
except ImportError:
    yaml = None

try:
    import requests
except ImportError:
    requests = None

GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
RESET = "\033[0m"

ENV_PATH = Path(".env")
DEFAULT_ENDPOINT = "http://localhost:8642/v1/chat/completions"


def print_header(text: str):
    print(f"\n{BLUE}{'=' * 60}{RESET}")
    print(f"{BLUE}{text}{RESET}")
    print(f"{BLUE}{'=' * 60}{RESET}\n")

def print_success(text: str):
    print(f"{GREEN}OK  {text}{RESET}")

def print_warning(text: str):
    print(f"{YELLOW}⚠  {text}{RESET}")

def print_error(text: str):
    print(f"{RED}✗  {text}{RESET}")

def print_info(text: str):
    print(f"  {text}")

def ask_yes_no(question: str, default: bool = True) -> bool:
    prefix = "Y/n" if default else "y/N"
    while True:
        answer = input(f"{question} [{prefix}]: ").strip().lower()
        if answer in ("", "y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        print_warning("Rispondi y o n")


# ---------------------------------------------------------------- env file

def load_env() -> dict:
    """Parse .env into a dict, keeping unrelated keys."""
    env = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                env[key.strip()] = value.strip()
    return env


def save_env(env: dict):
    lines = ["# Rail configuration (generated by setup.py) — DO NOT COMMIT"]
    for key in sorted(env):
        lines.append(f"{key}={env[key]}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    ENV_PATH.chmod(0o600)


# ---------------------------------------------------------------- helpers

def detect_local_hermes():
    """If a Hermes Agent install exists here, return (endpoint, api_key)."""
    hermes_config = Path.home() / ".hermes" / "config.yaml"
    if yaml is None or not hermes_config.exists():
        return None, None
    try:
        cfg = yaml.safe_load(hermes_config.read_text(encoding="utf-8")) or {}
        api = cfg.get("platforms", {}).get("api_server", {})
        if not api.get("enabled"):
            return None, None
        extra = api.get("extra", {}) or {}
        port = extra.get("port", 8642)
        key = extra.get("key", "")
        if not key:  # key may live in ~/.hermes/.env as API_SERVER_KEY
            env_path = Path.home() / ".hermes" / ".env"
            if env_path.exists():
                for line in env_path.read_text(encoding="utf-8").splitlines():
                    if line.strip().startswith("API_SERVER_KEY="):
                        key = line.split("=", 1)[1].strip().strip("'\"")
        return f"http://localhost:{port}/v1/chat/completions", (key or None)
    except Exception:
        return None, None


def normalize_endpoint(raw: str) -> str:
    """Accept full URL, https://host, or host:port and return a full endpoint."""
    raw = raw.strip().rstrip("/")
    if "/v1/" in raw:
        return raw
    if "://" not in raw:
        raw = "http://" + raw
    hostport = raw.split("://", 1)[1]
    if ":" not in hostport:
        raw += ":8642"
    return raw + "/v1/chat/completions"


def ping_api(endpoint: str, key: str, timeout: int = 12) -> bool:
    """GET /v1/models with Bearer auth: quick reachability+auth probe."""
    if requests is None:
        print_warning("Libreria 'requests' non installata: test di connessione saltato")
        return False
    base = endpoint.rsplit("/v1/", 1)[0]
    try:
        resp = requests.get(
            f"{base}/v1/models",
            headers={"Authorization": f"Bearer {key}"},
            timeout=timeout,
        )
        if resp.status_code == 200:
            print_success("Hermes api_server raggiungibile e chiave valida")
            return True
        if resp.status_code == 401:
            print_error("Risposta 401: endpoint raggiungibile ma API key errata")
        else:
            print_error(f"Endpoint risponde con HTTP {resp.status_code}")
    except Exception as exc:
        print_error(f"Endpoint non raggiungibile: {exc}")
    return False


# ---------------------------------------------------------------- sections

def setup_api(env: dict) -> bool:
    print_header("[1/3] Hermes API — direct connection (recommended)")

    print_info("Rail talks to your Hermes Agent over HTTP. Hermes usually runs on")
    print_info("ANOTHER machine: you need one reachable path to its api_server port")
    print_info("(8642). On the Hermes machine, enable in ~/.hermes/config.yaml:")
    print_info("  platforms: { api_server: { enabled: true } }   # then restart gateway")
    print()

    if not ask_yes_no("Use the direct Hermes API?", default=True):
        env.pop("HERMES_API_KEY", None)
        env.pop("HERMES_API_ENDPOINT", None)
        env["RAIL_API_ENABLED"] = "false"
        print_info("API disabled.")
        return True

    print_info("Where does the Hermes Agent run?")
    print_info("  [1] Remote host reached via SSH tunnel (most common: no server setup)")
    print_info("  [2] Remote host on a VPN / tailnet / public HTTPS endpoint")
    print_info("  [3] This same machine (rare)")
    where = ask_input_if("Where is Hermes?", "1")

    endpoint, key = DEFAULT_ENDPOINT, ""

    if where == "3":
        auto_ep, auto_key = detect_local_hermes()
        if auto_ep and auto_key:
            endpoint, key = auto_ep, auto_key
            print_success(f"Local Hermes detected: {endpoint} (key auto-detected)")
        else:
            print_warning("No local Hermes api_server found.")
            print_info("On the Hermes machine, enable 'api_server' + restart the gateway,")
            print_info("then rerun this wizard.")
            return True
    elif where == "2":
        endpoint = normalize_endpoint(
            ask_input_if("Reachable endpoint (https://host/path, ip:port or host:port)",
                         "http://10.0.0.10:8642"))
        key = getpass("Hermes API key (api_server key from the Hermes machine): ").strip()
    else:  # SSH tunnel: endpoint stays localhost, traffic goes through 'ssh -L'
        print_info("Rail will reach Hermes via an SSH tunnel (needs working ssh key")
        print_info("auth to the Hermes host). Hermes can stay bound to localhost.")
        target = ask_input_if("SSH target for Hermes host (user@host)")
        port = ask_input_if("Remote api_server port", "8642")
        env["RAIL_TUNNEL_TARGET"] = target
        env["RAIL_TUNNEL_PORT"] = port
        endpoint = f"http://localhost:{port}/v1/chat/completions"
        key = getpass("Hermes API key (same as extra.key on the Hermes machine): ").strip()

    if not key:
        print_warning("No API key given: the API channel stays disabled.")

    env["RAIL_API_ENABLED"] = "true" if key else "false"
    env["HERMES_API_ENDPOINT"] = endpoint
    if key:
        env["HERMES_API_KEY"] = key
        if requests is not None:
            print_info(f"Testing {endpoint} ...")
            if env.get("RAIL_TUNNEL_TARGET"):
                print_info("(via SSH tunnel: start it first with './rail-tunnel.sh',")
                print_info(" or run this test after the tunnel is up)")
            if not ping_api(endpoint, key):
                print_warning("Endpoint not reachable YET — if remote, start the tunnel/VPN,")
                print_warning(" then verify with: python setup.py --check")
    return True

    env["RAIL_API_ENABLED"] = "true" if key else "false"
    env["HERMES_API_ENDPOINT"] = endpoint
    if key:
        env["HERMES_API_KEY"] = key
        env.pop("HERMES_API_KEY_PLACEHOLDER", None)
        if requests is not None:
            print_info(f"Testing {endpoint} ...")
            if not ping_api(endpoint, key):
                print_warning("Channel saved but NOT working: check that the Hermes")
                print_warning("gateway is running and the api_server key matches.")
    return True


def ask_input_if(question: str, default: str = None) -> str:
    answer = input(f"{question}{f' (default: {default})' if default else ''}: ").strip()
    return answer or (default or "")


def setup_discord(env: dict) -> bool:
    print_header("[2/3] Discord — fallback channel (optional)")

    print_info("Rail can ALSO talk to Hermes through a shared Discord channel.")
    print_info("Only needed if Hermes runs on ANOTHER machine and you do NOT want")
    print_info("a direct/VPN connection. Needs a Discord bot token:")
    print_info("  1. https://discord.com/developers/applications -> new application")
    print_info("  2. Bot section -> reset/create token, enable MESSAGE CONTENT intent")
    print_info("  3. Invite the bot to the server where Hermes' bot also is")
    print()

    if not ask_yes_no("Use Discord as communication channel?", default=False):
        print_info("Discord disabled.")
        return True

    token = getpass("Discord Bot Token: ").strip()
    if not token:
        print_warning("No token given: Discord channel stays disabled.")
        return True

    env["DISCORD_BOT_TOKEN"] = token
    env["DISCORD_CHANNEL_ID"] = ask_input_if(
        "Discord Channel ID", env.get("DISCORD_CHANNEL_ID", "1552636595532865587"))
    env["HERMES_USER_ID"] = ask_input_if(
        "Hermes bot User ID (the bot that answers)",
        env.get("HERMES_USER_ID", "1538998656030609509"))
    return True


def setup_avatar(env: dict) -> bool:
    print_header("[3/3] Avatar size and position (optional)")

    if not ask_yes_no("Customize avatar size/position?", default=False):
        print_info("Keeping defaults (200x200, top-right).")
        return True

    config_path = Path("config.yaml")
    if not (yaml is not None and config_path.exists()):
        print_warning("PyYAML or config.yaml missing: skipping avatar config.")
        return True

    try:
        config = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except Exception:
        config = {}

    avatar = config.setdefault("avatar", {})
    width = ask_input_if("Avatar width (px)", "200")
    height = ask_input_if("Avatar height (px)", "200")
    position = ask_input_if(
        f"Avatar position {['top-left','top-right','bottom-left','bottom-right']}",
        "top-right")
    if position not in ("top-left", "top-right", "bottom-left", "bottom-right"):
        position = "top-right"

    avatar.update({"width": int(width), "height": int(height), "position": position})
    config_path.write_text(
        yaml.dump(config, default_flow_style=False, allow_unicode=True), encoding="utf-8")
    print_success("Avatar settings written in config.yaml")
    return True


# ---------------------------------------------------------------- modes

def run_check() -> bool:
    print_header("Rail connectivity check")
    env = load_env()
    ok = True

    api_enabled = env.get("RAIL_API_ENABLED", "true").lower() != "false"
    endpoint = env.get("HERMES_API_ENDPOINT", DEFAULT_ENDPOINT)
    key = env.get("HERMES_API_KEY", "")

    if api_enabled and key:
        print_info(f"API channel: {endpoint}")
        reachable = ping_api(endpoint, key)
        if not reachable and env.get("RAIL_TUNNEL_TARGET"):
            print_warning(f"Tunnel SSH probabilmente giù: avvia './rail-tunnel.sh' "
                          f"(target {env['RAIL_TUNNEL_TARGET']}) e riprova il check")
        ok &= reachable
    elif api_enabled and not key:
        print_warning("API enabled but HERMES_API_KEY missing: run 'python setup.py'")
        ok = False
    else:
        print_info("API channel: disabled")

    if env.get("DISCORD_BOT_TOKEN"):
        print_info("Discord channel: token configured (tested at app start)")
    else:
        print_info("Discord channel: not configured")

    if not api_enabled and not env.get("DISCORD_BOT_TOKEN"):
        print_error("No channel active: run 'python setup.py'")
        ok = False
    return ok


def main():
    if "--check" in sys.argv:
        sys.exit(0 if run_check() else 1)

    print_header("Rail Setup — channel configuration")

    env = load_env()
    if ENV_PATH.exists():
        print_info("Current configuration:")
        if env.get("RAIL_API_ENABLED", "true").lower() != "false":
            print_info(f"  API: {env.get('HERMES_API_ENDPOINT', DEFAULT_ENDPOINT)}")
        else:
            print_info("  API: disabled")
        print_info(f"  Discord: {'configured' if env.get('DISCORD_BOT_TOKEN') else 'not configured'}")
        print()
        if not ask_yes_no("Reconfigure the channels?", default=False):
            print_info("Configuration unchanged. Use '--check' to test connectivity.")
            return

    print_info("Choose at least ONE channel (API and/or Discord).")
    print()

    for step in (setup_api, setup_discord, setup_avatar):
        step(env)

    save_env(env)

    print_header("Done")
    api_on = env.get("RAIL_API_ENABLED", "false").lower() == "true" and env.get("HERMES_API_KEY")
    disc_on = bool(env.get("DISCORD_BOT_TOKEN"))
    if api_on:
        print_success("API channel: ENABLED")
    if disc_on:
        print_success("Discord channel: ENABLED")
    if not (api_on or disc_on):
        print_warning("No channel active: rerun 'python setup.py'")
    print()
    print_info("Check anytime:   python setup.py --check")
    print_info("Run the avatar:  python -m hermes_avatar.main")


if __name__ == "__main__":
    main()
